package ca.ulaval.glo2004.GUI;

public class AppMasterJFrame extends javax.swing.JFrame {

    public AppMasterJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MenuBar = new javax.swing.JMenuBar();
        FileMenu = new javax.swing.JMenu();
        newProjectMenu = new javax.swing.JMenuItem();
        openMenu = new javax.swing.JMenuItem();
        saveMenu = new javax.swing.JMenuItem();
        exportImage = new javax.swing.JMenuItem();
        EditMenu = new javax.swing.JMenu();
        ViewMenu = new javax.swing.JMenu();
        showGridCheckBox = new javax.swing.JCheckBoxMenuItem();
        magnetizeGrid = new javax.swing.JCheckBoxMenuItem();
        QuestionMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        FileMenu.setText("File");

        newProjectMenu.setText("New Project");
        FileMenu.add(newProjectMenu);

        openMenu.setText("Open");
        FileMenu.add(openMenu);

        saveMenu.setText("Save");
        FileMenu.add(saveMenu);

        exportImage.setText("Export as image...");
        exportImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportImageActionPerformed(evt);
            }
        });
        FileMenu.add(exportImage);

        MenuBar.add(FileMenu);

        EditMenu.setText("Edit");
        MenuBar.add(EditMenu);

        ViewMenu.setText("View");

        showGridCheckBox.setText("Show grid");
        ViewMenu.add(showGridCheckBox);

        magnetizeGrid.setText("Magnetize Grid");
        magnetizeGrid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                magnetizeGridActionPerformed(evt);
            }
        });
        ViewMenu.add(magnetizeGrid);

        MenuBar.add(ViewMenu);

        QuestionMenu.setText("?");
        MenuBar.add(QuestionMenu);

        setJMenuBar(MenuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void magnetizeGridActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_magnetizeGridActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_magnetizeGridActionPerformed

    private void exportImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportImageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_exportImageActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu EditMenu;
    private javax.swing.JMenu FileMenu;
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JMenu QuestionMenu;
    private javax.swing.JMenu ViewMenu;
    protected javax.swing.JMenuItem exportImage;
    protected javax.swing.JCheckBoxMenuItem magnetizeGrid;
    public javax.swing.JMenuItem newProjectMenu;
    protected javax.swing.JMenuItem openMenu;
    public javax.swing.JMenuItem saveMenu;
    protected javax.swing.JCheckBoxMenuItem showGridCheckBox;
    // End of variables declaration//GEN-END:variables
}
